// <auto-generated />
using System;
using GeoGoAPI._models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoGoAPI.Migrations
{
    [DbContext(typeof(GeoGoDbContext))]
    [Migration("20251206224101_ChangeVObjects")]
    partial class ChangeVObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("GeoGoAPI._models.entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.CategoryWeights", b =>
                {
                    b.Property<int>("UserTwinId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.HasKey("UserTwinId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryWeights");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.InteractionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UserTwinId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VirtualAnimationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VirtualObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VirtualPlaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VirtualObjectId");

                    b.HasIndex("VirtualPlaceId");

                    b.HasIndex("UserTwinId", "PlaceId");

                    b.ToTable("InteractionEvents");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.PlaceLikes", b =>
                {
                    b.Property<int>("UserTwinId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.HasKey("UserTwinId", "PlaceId");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlaceLikes");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.UserTwin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserTwins");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.VirtualObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUrlTexture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PX")
                        .HasColumnType("REAL");

                    b.Property<float>("PY")
                        .HasColumnType("REAL");

                    b.Property<float>("PZ")
                        .HasColumnType("REAL");

                    b.Property<float>("RX")
                        .HasColumnType("REAL");

                    b.Property<float>("RY")
                        .HasColumnType("REAL");

                    b.Property<float>("RZ")
                        .HasColumnType("REAL");

                    b.Property<float>("SX")
                        .HasColumnType("REAL");

                    b.Property<float>("SY")
                        .HasColumnType("REAL");

                    b.Property<float>("SZ")
                        .HasColumnType("REAL");

                    b.Property<string>("TextDisplayed")
                        .HasColumnType("TEXT");

                    b.Property<int>("VirtualPlaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VirtualPlaceId");

                    b.ToTable("VirtualObjects");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.VirtualPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId")
                        .IsUnique();

                    b.ToTable("VirtualPlaces");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.CategoryWeights", b =>
                {
                    b.HasOne("GeoGoAPI._models.entities.Category", "Category")
                        .WithMany("CategoryWeights")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoGoAPI._models.entities.UserTwin", "UserTwin")
                        .WithMany("CategoryWeights")
                        .HasForeignKey("UserTwinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UserTwin");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.InteractionEvent", b =>
                {
                    b.HasOne("GeoGoAPI._models.entities.UserTwin", "UserTwin")
                        .WithMany()
                        .HasForeignKey("UserTwinId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeoGoAPI._models.entities.VirtualObject", "VirtualObject")
                        .WithMany("InteractionEvents")
                        .HasForeignKey("VirtualObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoGoAPI._models.entities.VirtualPlace", "VirtualPlace")
                        .WithMany("InteractionEvents")
                        .HasForeignKey("VirtualPlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoGoAPI._models.entities.PlaceLikes", "PlaceLike")
                        .WithMany("InteractionEvents")
                        .HasForeignKey("UserTwinId", "PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlaceLike");

                    b.Navigation("UserTwin");

                    b.Navigation("VirtualObject");

                    b.Navigation("VirtualPlace");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.Place", b =>
                {
                    b.HasOne("GeoGoAPI._models.entities.Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.PlaceLikes", b =>
                {
                    b.HasOne("GeoGoAPI._models.entities.Place", "Place")
                        .WithMany("PlaceLikes")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoGoAPI._models.entities.UserTwin", "UserTwin")
                        .WithMany("PlaceLikes")
                        .HasForeignKey("UserTwinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("UserTwin");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.UserTwin", b =>
                {
                    b.HasOne("GeoGoAPI._models.entities.AppUser", "User")
                        .WithOne("Twin")
                        .HasForeignKey("GeoGoAPI._models.entities.UserTwin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.VirtualObject", b =>
                {
                    b.HasOne("GeoGoAPI._models.entities.VirtualPlace", "VirtualPlace")
                        .WithMany("VirtualObjects")
                        .HasForeignKey("VirtualPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualPlace");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.VirtualPlace", b =>
                {
                    b.HasOne("GeoGoAPI._models.entities.Place", "Place")
                        .WithOne("VirtualPlace")
                        .HasForeignKey("GeoGoAPI._models.entities.VirtualPlace", "PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.AppUser", b =>
                {
                    b.Navigation("Twin");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.Category", b =>
                {
                    b.Navigation("CategoryWeights");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.Place", b =>
                {
                    b.Navigation("PlaceLikes");

                    b.Navigation("VirtualPlace");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.PlaceLikes", b =>
                {
                    b.Navigation("InteractionEvents");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.UserTwin", b =>
                {
                    b.Navigation("CategoryWeights");

                    b.Navigation("PlaceLikes");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.VirtualObject", b =>
                {
                    b.Navigation("InteractionEvents");
                });

            modelBuilder.Entity("GeoGoAPI._models.entities.VirtualPlace", b =>
                {
                    b.Navigation("InteractionEvents");

                    b.Navigation("VirtualObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
